extraction:
  cpp:
    prepare:
      packages:
        - cmake
        - pkg-config
        - libqt5core5a
        - libqt5gui5
        - libqt5network5
        - libqt5concurrent5
        - libqt5printsupport5
        - libqt5sql5
        - libqt5svg5
        - libqt5svg5-dev
        - qtdeclarative5-dev
        - libqt5quickwidgets5
        - libqt5widgets5
        - qtbase5-dev
        - qtwebengine5-dev
    configure:
      command:
        - mkdir build
        - cd build
        - cmake ..
    index:
      build_command:
        - cd build
        - make
  javascript:
    index:
      exclude:
        - src/app/assets
